export const weatherConstant = {
  TEST: "TEST",

  GET_WEATHER: "GET_WEATHER",

  UPDATE_WEATHER: "UPDATE_WEATHER",
  UPDATE_WEATHER_LOADING: "UPDATE_WEATHER_LOADING",
  UPDATE_WEATHER_SUCCESS: "UPDATE_WEATHER_SUCCESS",
  UPDATE_WEATHER_FAIL: "UPDATE_WEATHER_FAIL",
};
